name: Go Build and Release

on:
  push:
    # branches: [main]
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.9
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build Program linux_amd64
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o ddn_${{ github.ref_name }}_linux_amd64 ./main.go
      - name: Build Program linux_arm64
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o ddn_${{ github.ref_name }}_linux_arm64 ./main.go
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          files: |
            ddn_${{ github.ref_name }}_linux_amd64
            ddn_${{ github.ref_name }}_linux_arm64
